iso_name="FunkyOS"
iso_label="FUNKY_GHOST"
iso_publisher="FunkyOS Dev"
iso_application="Ghost System"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux' 'uefi.grub')
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
