# FunkyOS Neobrutalist Identity
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 5
    col.active_border = rgba(000000ff)
    col.inactive_border = rgba(555555ff)
}

decoration {
    rounding = 0
    drop_shadow = true
    shadow_range = 0
    shadow_offset = 10 10
    col.shadow = rgba(000000ee)
}
